# Generated by Django 4.1.7 on 2023-03-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created'], 'verbose_name_plural': 'My Posts'},
        ),
    ]
